### ISSUE TITLE
Multiprocessing with basescript

### ISSUE THREAD

**Issue by IdavalapatiRamanjaneyulu** [deep-compute/basescript#91] opened 2019-07-24 06:04 UTC
Multiprocessing is not working with basescript (method is not getting called). If I remove basescript then it is working.

**Multiprocessing with basescript**
```python
from multiprocessing import Pool

from basescript import BaseScript

class VocabGen(BaseScript):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def process_single_file(self):
        processes = []
        pool = Pool()
        for i in range(10):
            p = pool.apply_async(self.sleep_two_secs)
            processes.append(p)
            start = i 

        for p in processes:
            p.wait()

    def sleep_two_secs(self):
        print("Came inside")

    def run(self):
        self.process_single_file()

if __name__ == '__main__':
    VocabGen().start()
```
**RUN**: python3 base.py run
**Output**: Empty output. But exepected is "Came inside" should get print 10 times.

**Multiprocessing without basescript**
```python
from multiprocessing import Pool

class VocabGen():
    def __init__(self, *args, **kwargs):
        pass

    def process_single_file(self):
        processes = []
        pool = Pool()
        for i in range(10):
            p = pool.apply_async(self.sleep_two_secs)
            processes.append(p)
            start = i 

        for p in processes:
            p.wait()

    def sleep_two_secs(self):
        print("Came inside")

    def run(self):
        self.process_single_file()

if __name__ == '__main__':
    v = VocabGen()
    v.run()
```
**RUN**: python3 test.py
**Output**: "Came inside" is getting print for 10 times.

**Comment by jaswanth098** [comment] 2019-07-24 08:34
@RamanjaneyuluIdavalapati The problem is with argparse
in multiprocessing code it is calling `__reduce_ex__` function of ArgumentParser class which returns something called `ArgumentParser.__init__.<locals>.identity` in multiprocessing they are throwing error in if something like locals is present in `__reduce_ex__`
I don't think we can solve this problem with basescript, but anyway will think of a way to patch this one
until then add classmethod for the function that you want to send to multiprocessing then it will work fine
Eg:
```python
from multiprocessing import Pool

from basescript import BaseScript

class VocabGen(BaseScript):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def process_single_file(self):
        processes = []
        pool = Pool()
        for i in range(10):
            p = pool.apply_async(self.sleep_two_secs)
            processes.append(p)
            start = i 

        for p in processes:
            p.wait()

    @classmethod
    def sleep_two_secs(self):
        print("Came inside")

    def run(self):
        self.process_single_file()

if __name__ == '__main__':
    VocabGen().start()

```

CC: @prashanthellina

**Comment by prashanthellina** [comment] 2019-07-24 09:56
@RamanjaneyuluIdavalapati @jaswanth098 AFAIK, `multiprocessing` logic will attempt to transfer a serialized version of the function object across from parent to child process. It is therefore better to keep the function object minimal. i.e Pass a non object method instead of an object method which has so much state attached to it (like self.args etc).

**Comment by prashanthellina** [comment] 2019-07-24 09:57
We don't have to change anything in `basescript` for this immediately.

**Comment by jaswanth098** [comment] 2019-08-26 05:24
A we don't have to do anything in basescript closing this

**Closed as completed by jaswanth098** 2019-08-26 05:24 UTC
Labels: inprogress-status, moveto-inprogress-1m
